# Generated by Django 6.0.1 on 2026-06-27 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('free', 'Gratuito'), ('pro', 'Pro')], max_length=10, unique=True)),
                ('nome_exibicao', models.CharField(max_length=50)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('requer_quiz', models.BooleanField(default=False, help_text='Se True, obriga o usuário a responder o questionário de risco')),
                ('acesso_personalizacao', models.BooleanField(default=False, help_text='Se True, gera carteira ideal personalizada por perfil de risco')),
                ('acesso_otimizacao_markowitz', models.BooleanField(default=False, help_text='Se True, libera os filtros de risco/retorno e os 4 modelos de otimização')),
                ('acesso_simulacao_substituicao', models.BooleanField(default=False, help_text="Se True, libera o 'trocar ativo' com cálculo de impacto no Sharpe")),
                ('limite_ativos_visiveis', models.IntegerField(default=5, help_text='Quantos ativos no ranking/carteira o usuário pode ver. NULL = ilimitado')),
                ('limite_recalculos_mes', models.IntegerField(blank=True, help_text='Quantas vezes por mês pode gerar nova recomendação. NULL = ilimitado', null=True)),
                ('acesso_historico_completo', models.BooleanField(default=False, help_text='Free só vê o último ano de KPIs; Pro vê os 8 anos completos')),
                ('acesso_sentimento_mercado', models.BooleanField(default=False, help_text='Análise de sentimento de notícias — só Pro')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('pendente', 'Pagamento pendente')], default='ativa', max_length=10)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, help_text='NULL para o plano free (sem vencimento). Pro vence em 30 dias.', null=True)),
                ('recalculos_usados_mes', models.IntegerField(default=0)),
                ('mes_referencia', models.DateField(default=django.utils.timezone.now)),
                ('pagamento_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pagamento_metodo', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
            },
        ),
    ]
