# Generated by Django 6.0.1 on 2026-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='limite_ativos_visiveis',
            field=models.IntegerField(blank=True, default=5, help_text='Quantos ativos no ranking/carteira o usuário pode ver. NULL = ilimitado', null=True),
        ),
    ]
