"""
Execute dentro de Insight_invest:
  python corrigir_b3_extractor.py
"""
import os

destino = os.path.join("services", "extractors", "b3_extractor.py")

linhas = [
    'import io, logging, os, time\n',
    'import pandas as pd\n',
    'import requests\n',
    '\n',
    'logger = logging.getLogger(__name__)\n',
    'CACHE_PATH = "data/tickers_b3.csv"\n',
    '\n',
    'B3_URL = (\n',
    '    "https://sistemaswebb3-listados.b3.com.br/listedCompaniesProxy/"\n',
    '    "CompanyCall/GetInitialCompanies/"\n',
    ')\n',
    'CVM_URL = "https://dados.cvm.gov.br/dados/CIA_ABERTA/CAD/DADOS/cad_cia_aberta.csv"\n',
    '\n',
    'HEADERS_B3 = {\n',
    '    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",\n',
    '    "Accept": "application/json, text/plain, */*",\n',
    '    "Content-Type": "application/json",\n',
    '    "Origin": "https://www.b3.com.br",\n',
    '    "Referer": "https://www.b3.com.br/",\n',
    '}\n',
    'HEADERS_CVM = {"User-Agent": "InsightInvest/1.0"}\n',
    '\n',
    '\n',
    'def _buscar_pagina_b3(pagina):\n',
    '    payload = {"language": "pt-br", "pageNumber": pagina, "pageSize": 120}\n',
    '    try:\n',
    '        r = requests.post(B3_URL, json=payload, headers=HEADERS_B3, timeout=15)\n',
    '        if r.status_code != 200 or not r.text.strip():\n',
    '            return []\n',
    '        dados = r.json()\n',
    '        if isinstance(dados, list):\n',
    '            return dados\n',
    '        if isinstance(dados, dict):\n',
    '            return dados.get("companies", dados.get("results", []))\n',
    '    except Exception as e:\n',
    '        logger.warning(f"Pagina {pagina}: {e}")\n',
    '    return []\n',
    '\n',
    '\n',
    'def buscar_empresas_b3():\n',
    '    registros, pagina = [], 1\n',
    '    print("Buscando empresas da B3", end="", flush=True)\n',
    '    while True:\n',
    '        empresas = _buscar_pagina_b3(pagina)\n',
    '        if not empresas:\n',
    '            break\n',
    '        for emp in empresas:\n',
    '            ticker = str(emp.get("issuingCompany", "") or "").strip().upper()\n',
    '            cod_cvm = str(emp.get("codeCVM", "")).strip().zfill(6)\n',
    '            if ticker and len(ticker) >= 4:\n',
    '                registros.append({\n',
    '                    "ticker": ticker,\n',
    '                    "nome_pregao": str(emp.get("companyName", "")).strip(),\n',
    '                    "cod_cvm": cod_cvm,\n',
    '                    "segmento": str(emp.get("segment", "")).strip(),\n',
    '                })\n',
    '        print(".", end="", flush=True)\n',
    '        pagina += 1\n',
    '        time.sleep(0.4)\n',
    '    print(f" {len(registros)} empresas")\n',
    '    if not registros:\n',
    '        return pd.DataFrame()\n',
    '    return pd.DataFrame(registros).drop_duplicates(subset=["ticker"])\n',
    '\n',
    '\n',
    'def buscar_cnpj_cvm():\n',
    '    print("Baixando CNPJs da CVM...")\n',
    '    r = requests.get(CVM_URL, headers=HEADERS_CVM, timeout=30)\n',
    '    r.raise_for_status()\n',
    '    df = pd.read_csv(io.StringIO(r.text), sep=";", encoding="latin-1", dtype=str)\n',
    '    df.columns = [c.strip() for c in df.columns]\n',
    '    cols = {c.upper(): c for c in df.columns}\n',
    '    col_cnpj  = cols.get("CNPJ_CIA")\n',
    '    col_cvm   = cols.get("CD_CVM") or cols.get("COD_CVM")\n',
    '    col_nome  = cols.get("DENOM_SOCIAL") or cols.get("DENOM_CIA") or cols.get("DENOM_COMERC")\n',
    '    col_setor = cols.get("SETOR_ATIV") or cols.get("SETOR")\n',
    '    col_sit   = cols.get("SIT") or cols.get("SITUACAO")\n',
    '    if not col_cnpj or not col_cvm:\n',
    '        print(f"AVISO: colunas disponiveis: {df.columns.tolist()}")\n',
    '        return pd.DataFrame()\n',
    '    resultado = pd.DataFrame({\n',
    '        "cnpj":     df[col_cnpj].str.strip(),\n',
    '        "cod_cvm":  df[col_cvm].str.strip().str.zfill(6),\n',
    '        "nome_cvm": df[col_nome].str.strip() if col_nome else "",\n',
    '        "setor":    df[col_setor].str.strip().apply(_limpar_setor) if col_setor else "",\n',
    '        "sit":      df[col_sit].str.strip().str.upper() if col_sit else "ATIVO",\n',
    '    })\n',
    '    ativas = resultado[resultado["sit"] == "ATIVO"].copy()\n',
    '    print(f"  {len(ativas):,} empresas ativas na CVM")\n',
    '    return ativas\n',
    '\n',
    '\n',
    'def construir_mapa_ticker_cnpj():\n',
    '    df_b3  = buscar_empresas_b3()\n',
    '    df_cvm = buscar_cnpj_cvm()\n',
    '    if df_b3.empty and df_cvm.empty:\n',
    '        raise RuntimeError("Falha ao obter dados da B3 e da CVM.")\n',
    '    if df_b3.empty:\n',
    '        print("AVISO: B3 nao respondeu. Criando ativos sem ticker.")\n',
    '        df_cvm["ticker"] = df_cvm["nome_cvm"].str[:4].str.upper() + "3"\n',
    '        df_cvm["tipo"] = "acao"\n',
    '        return df_cvm[["ticker","nome_cvm","cnpj","setor","cod_cvm","tipo"]].rename(columns={"nome_cvm":"nome"})\n',
    '    if not df_cvm.empty:\n',
    '        df = pd.merge(df_b3, df_cvm, on="cod_cvm", how="left")\n',
    '        df["nome"] = df["nome_cvm"].fillna(df["nome_pregao"])\n',
    '    else:\n',
    '        df = df_b3.copy()\n',
    '        df["cnpj"]  = None\n',
    '        df["setor"] = df["segmento"]\n',
    '        df["nome"]  = df["nome_pregao"]\n',
    '    df["tipo"] = df["ticker"].apply(_inferir_tipo)\n',
    '    df = df.drop_duplicates(subset=["ticker"]).reset_index(drop=True)\n',
    '    com_cnpj = df["cnpj"].notna().sum()\n',
    '    print(f"RESULTADO FINAL: {len(df)} tickers | {com_cnpj} com CNPJ")\n',
    '    return df[["ticker","nome","cnpj","setor","cod_cvm","tipo"]]\n',
    '\n',
    '\n',
    'def salvar_mapa_csv(df, caminho=CACHE_PATH):\n',
    '    os.makedirs(os.path.dirname(caminho), exist_ok=True)\n',
    '    df.to_csv(caminho, index=False, encoding="utf-8")\n',
    '    print(f"Cache salvo: {caminho}")\n',
    '\n',
    '\n',
    'def carregar_mapa_csv(caminho=CACHE_PATH):\n',
    '    if os.path.exists(caminho):\n',
    '        return pd.read_csv(caminho, dtype={"cnpj": str, "cod_cvm": str})\n',
    '    return pd.DataFrame()\n',
    '\n',
    '\n',
    'def _inferir_tipo(ticker):\n',
    '    t = str(ticker).upper()\n',
    '    if t.endswith("11"): return "fii"\n',
    '    if t.endswith("34"): return "bdr"\n',
    '    if t.endswith("F"):  return "renda_fixa"\n',
    '    return "acao"\n',
    '\n',
    '\n',
    'def _limpar_setor(setor):\n',
    '    if not setor or str(setor).strip() in ("nan", ""):\n',
    '        return ""\n',
    '    return str(setor).split(". ", 1)[-1].strip()[:100]\n',
]

if not os.path.isdir(os.path.dirname(destino)):
    print(f"ERRO: pasta nao encontrada: {os.path.dirname(destino)}")
    print("Rode este script dentro da pasta Insight_invest/")
else:
    with open(destino, "w", encoding="utf-8") as f:
        f.writelines(linhas)
    print(f"OK! Arquivo gravado em: {destino}")
    print()
    print("Agora execute:")
    print("  python manage.py load_tickers_b3")