"""
Execute dentro de Insight_invest:
  python corrigir_calcular_scores.py
"""
import os

destino = os.path.join("scoring", "management", "commands", "calcular_scores.py")

linhas = [
    '"""\n',
    'Salve em: scoring/management/commands/calcular_scores.py\n',
    '\n',
    'Execucao:\n',
    '  python manage.py calcular_scores\n',
    '  python manage.py calcular_scores --perfil conservador\n',
    '  python manage.py calcular_scores --usuario carolina\n',
    '  python manage.py calcular_scores --apenas-scores\n',
    '"""\n',
    '\n',
    'import logging\n',
    'from datetime import date\n',
    '\n',
    'from django.core.management.base import BaseCommand, CommandError\n',
    'from django.db import transaction\n',
    '\n',
    'logger = logging.getLogger(__name__)\n',
    '\n',
    '\n',
    'class Command(BaseCommand):\n',
    '    help = "Calcula scores por camada e score_final para todos os ativos"\n',
    '\n',
    '    def add_arguments(self, parser):\n',
    '        parser.add_argument(\n',
    '            "--perfil",\n',
    '            type=str,\n',
    '            default="intermediario",\n',
    '            choices=["conservador", "intermediario", "arrojado"],\n',
    '            help="Perfil de risco para ponderar os scores",\n',
    '        )\n',
    '        parser.add_argument(\n',
    '            "--usuario",\n',
    '            type=str,\n',
    '            default=None,\n',
    '            help="Username para gerar recomendacao personalizada",\n',
    '        )\n',
    '        parser.add_argument(\n',
    '            "--apenas-scores",\n',
    '            action="store_true",\n',
    '            help="So calcula e salva ScoreAtivo, sem gerar recomendacao",\n',
    '        )\n',
    '\n',
    '    def handle(self, *args, **options):\n',
    '        # Importa de scoring.services (services esta dentro do app scoring)\n',
    '        try:\n',
    '            from scoring.services.motor_scoring import calcular_scores_todos_ativos\n',
    '            from scoring.services.recomendacao import gerar_recomendacao\n',
    '        except ModuleNotFoundError as e:\n',
    '            raise CommandError(\n',
    '                f"Modulo nao encontrado: {e}\\n"\n',
    '                "Verifique se scoring/services/motor_scoring.py existe\\n"\n',
    '                "e se ha __init__.py em scoring/services/"\n',
    '            )\n',
    '\n',
    '        from scoring.models import ScoreAtivo\n',
    '        from market_data.models import KpiMacro\n',
    '\n',
    '        perfil        = options["perfil"]\n',
    '        username      = options.get("usuario")\n',
    '        apenas_scores = options.get("apenas_scores", False)\n',
    '\n',
    '        self.stdout.write(f"Calculando scores | perfil: {perfil}\\n")\n',
    '\n',
    '        # --- Passo 1: Calcula todos os scores ---\n',
    '        self.stdout.write("[1/3] Calculando scores por camada...")\n',
    '        df_scores = calcular_scores_todos_ativos(\n',
    '            data_ref=date.today(),\n',
    '            perfil=perfil,\n',
    '        )\n',
    '\n',
    '        if df_scores.empty:\n',
    '            raise CommandError(\n',
    '                "Nenhum ativo com dados suficientes.\\n"\n',
    '                "Rode antes: python manage.py load_cvm_data"\n',
    '            )\n',
    '\n',
    '        top5 = df_scores.nlargest(5, "score_final")["ticker"].tolist()\n',
    '        self.stdout.write(self.style.SUCCESS(\n',
    '            f"    {len(df_scores)} ativos calculados\\n"\n',
    '            f"    Score medio: {df_scores[\'score_final\'].mean():.1f}\\n"\n',
    '            f"    Top 5: {top5}\\n"\n',
    '        ))\n',
    '\n',
    '        # --- Passo 2: Salva ScoreAtivo no banco ---\n',
    '        self.stdout.write("[2/3] Salvando ScoreAtivo...")\n',
    '        kpi_macro = KpiMacro.objects.order_by("-data_ref").first()\n',
    '        salvos = 0\n',
    '\n',
    '        with transaction.atomic():\n',
    '            for _, row in df_scores.iterrows():\n',
    '                ScoreAtivo.objects.update_or_create(\n',
    '                    ativo_id     = int(row["ativo_id"]),\n',
    '                    data_calculo = date.today(),\n',
    '                    defaults={\n',
    '                        "score_micro":      row.get("score_micro"),\n',
    '                        "score_macro":      row.get("score_macro"),\n',
    '                        "score_time":       row.get("score_time"),\n',
    '                        "score_sentimento": row.get("score_sentimento"),\n',
    '                        "score_final":      row["score_final"],\n',
    '                        "kpi_macro_ref":    kpi_macro,\n',
    '                    },\n',
    '                )\n',
    '                salvos += 1\n',
    '\n',
    '        self.stdout.write(self.style.SUCCESS(f"    {salvos} ScoreAtivo salvos\\n"))\n',
    '\n',
    '        if apenas_scores:\n',
    '            self.stdout.write(self.style.SUCCESS("Concluido!"))\n',
    '            return\n',
    '\n',
    '        # --- Passo 3: Gera recomendacao para usuario ---\n',
    '        if username:\n',
    '            self.stdout.write(f"[3/3] Gerando recomendacao para \'{username}\'...")\n',
    '            try:\n',
    '                from users.models import User\n',
    '                user = User.objects.get(username=username)\n',
    '            except Exception:\n',
    '                raise CommandError(f"Usuario \'{username}\' nao encontrado.")\n',
    '\n',
    '            perfil_usuario = user.perfil_risco.tipo if user.perfil_risco else perfil\n',
    '            rec = gerar_recomendacao(user, df_scores, perfil_usuario)\n',
    '\n',
    '            if rec:\n',
    '                self.stdout.write(self.style.SUCCESS(\n',
    '                    f"    Recomendacao #{rec.id} gerada com {rec.itens.count()} ativos!\\n"\n',
    '                    f"    Admin: http://127.0.0.1:8000/admin/scoring/recomendacao/{rec.id}/"\n',
    '                ))\n',
    '            else:\n',
    '                self.stdout.write(self.style.WARNING("    Falha ao gerar recomendacao."))\n',
    '        else:\n',
    '            self.stdout.write(\n',
    '                "[3/3] Para gerar recomendacao:\\n"\n',
    '                "  python manage.py calcular_scores --usuario seu_username\\n"\n',
    '            )\n',
    '\n',
    '        self.stdout.write(self.style.SUCCESS(\n',
    '            "\\nVer resultados:\\n"\n',
    '            "  http://127.0.0.1:8000/admin/scoring/scoreativo/\\n"\n',
    '        ))\n',
]

if not os.path.isdir(os.path.dirname(destino)):
    print(f"ERRO: pasta nao encontrada: {os.path.dirname(destino)}")
    print("Verifique se scoring/management/commands/ existe.")
else:
    with open(destino, "w", encoding="utf-8") as f:
        f.writelines(linhas)
    print(f"OK! {destino} corrigido.")
    print()
    print("Agora verifique se scoring/services/__init__.py existe:")
    init_path = os.path.join("scoring", "services", "__init__.py")
    if not os.path.exists(init_path):
        os.makedirs(os.path.dirname(init_path), exist_ok=True)
        open(init_path, "w").close()
        print(f"  Criado: {init_path}")
    else:
        print(f"  OK: {init_path} ja existe")
    print()
    print("Execute:")
    print("  python manage.py calcular_scores --apenas-scores")