# Generated by Django 6.0.1 on 2026-05-01 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref', models.DateField(unique=True)),
                ('selic', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('ipca_mensal', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('igpm_mensal', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('pib_trimestral', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('desemprego', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('dolar_brl', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('risco_brasil', models.DecimalField(blank=True, decimal_places=2, help_text='CDS 5 anos / EMBI+', max_digits=8, null=True)),
                ('ibovespa_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume_negociado_b3', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'KPI Macro',
                'ordering': ['-data_ref'],
            },
        ),
        migrations.CreateModel(
            name='KpiMicro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref', models.DateField()),
                ('roe', models.DecimalField(blank=True, decimal_places=4, help_text='Return on Equity', max_digits=8, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=4, help_text='Return on Assets', max_digits=8, null=True)),
                ('margem_liquida', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('margem_ebitda', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('divida_liquida', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('divida_ebitda', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('crescimento_receita', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('crescimento_lucro', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pl', models.DecimalField(blank=True, decimal_places=4, help_text='Preço/Lucro', max_digits=8, null=True)),
                ('pvpa', models.DecimalField(blank=True, decimal_places=4, help_text='Preço/Valor Patrimonial', max_digits=8, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('dy', models.DecimalField(blank=True, decimal_places=4, help_text='Dividend Yield', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'KPI Micro',
                'ordering': ['-data_ref'],
            },
        ),
        migrations.CreateModel(
            name='KpiTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref', models.DateField()),
                ('volume_medio_20d', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('volume_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('volatilidade_30d', models.DecimalField(blank=True, decimal_places=6, help_text='Desvio padrão anualizado 30d', max_digits=8, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('retorno_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('retorno_3m', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('retorno_12m', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=2, help_text='RSI 14 períodos (0-100)', max_digits=5, null=True)),
                ('media_movel_50', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('media_movel_200', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'KPI Time',
                'ordering': ['-data_ref'],
            },
        ),
        migrations.CreateModel(
            name='SentimentoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref', models.DateField()),
                ('fonte', models.CharField(choices=[('twitter', 'X / Twitter'), ('reddit', 'Reddit'), ('infomoney', 'InfoMoney'), ('valor', 'Valor Econômico'), ('bloomberg', 'Bloomberg Brasil'), ('outros', 'Outros')], max_length=20)),
                ('score_sentimento', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('volume_mencoes', models.IntegerField(default=0)),
                ('resumo_nlp', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sentimento de Mercado',
                'ordering': ['-data_ref'],
            },
        ),
    ]
