# Generated by Django 6.0.1 on 2026-05-01 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpimicro',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis_micro', to='portfolio.ativo'),
        ),
        migrations.AddField(
            model_name='kpitime',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis_time', to='portfolio.ativo'),
        ),
        migrations.AddField(
            model_name='sentimentomercado',
            name='ativo',
            field=models.ForeignKey(blank=True, help_text='Nulo = sentimento macroeconômico geral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentimentos', to='portfolio.ativo'),
        ),
        migrations.AlterUniqueTogether(
            name='kpimicro',
            unique_together={('ativo', 'data_ref')},
        ),
        migrations.AlterUniqueTogether(
            name='kpitime',
            unique_together={('ativo', 'data_ref')},
        ),
    ]
