# Generated by Django 6.0.1 on 2026-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_kpimacro_balanca_comercial_kpimacro_exportacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimacro',
            name='desemprego',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='kpimacro',
            name='ibc_br',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='kpimacro',
            name='pib_trimestral',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
