# Generated by Django 6.0.1 on 2026-05-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_alter_kpimacro_desemprego_alter_kpimacro_ibc_br_and_more'),
        ('portfolio', '0003_ativo_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpitime',
            name='rsi_14',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RSI 14 períodos', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='kpitime',
            name='volatilidade_30d',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentomercado',
            name='ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentimentos', to='portfolio.ativo'),
        ),
    ]
