# Generated by Django 6.0.1 on 2026-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_alter_kpitime_rsi_14_alter_kpitime_volatilidade_30d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimicro',
            name='crescimento_lucro',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='crescimento_receita',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='divida_ebitda',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='divida_liquida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='dy',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Dividend Yield', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='ev_ebitda',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='margem_ebitda',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='margem_liquida',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='pl',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço/Lucro', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='pvpa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço/Valor Patrimonial', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='roa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Return on Assets', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='kpimicro',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Return on Equity', max_digits=18, null=True),
        ),
    ]
