# Generated by Django 6.0.1 on 2026-05-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_alter_kpimicro_crescimento_lucro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpimicro',
            name='distribuicao_dividendos',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Payout', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='dividendo_por_acao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='giro_ativo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='indice_rentabilidade_acao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='liquidez_corrente',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='liquidez_geral',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='liquidez_imediata',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='liquidez_seca',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='lucro_por_acao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='prazo_retorno',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='rentabilidade_dividendos',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='kpimicro',
            name='valor_patrimonial_acao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
