# Generated by Django 6.0.1 on 2026-07-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0007_kpimicro_distribuicao_dividendos_and_more'),
        ('portfolio', '0003_ativo_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiEstatistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateField()),
                ('janela_dias', models.IntegerField(choices=[(63, '3 meses'), (126, '6 meses'), (252, '1 ano'), (504, '2 anos'), (756, '3 anos')], default=252, help_text='Janela de pregões usada no cálculo')),
                ('media_retorno', models.DecimalField(blank=True, decimal_places=8, help_text='Média dos retornos log diários', max_digits=12, null=True)),
                ('mediana_retorno', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('variancia_retorno', models.DecimalField(blank=True, decimal_places=10, help_text='Variância dos retornos log diários', max_digits=12, null=True)),
                ('dp_retorno', models.DecimalField(blank=True, decimal_places=8, help_text='Desvio padrão dos retornos log diários', max_digits=10, null=True)),
                ('volatilidade_anual', models.DecimalField(blank=True, decimal_places=6, help_text='Desvio padrão anualizado (dp_diario × √252)', max_digits=8, null=True)),
                ('cv', models.DecimalField(blank=True, decimal_places=6, help_text='Coeficiente de variação = dp / |média| (risco relativo)', max_digits=10, null=True)),
                ('skewness', models.DecimalField(blank=True, decimal_places=6, help_text='Assimetria: >0 cauda direita, <0 cauda esquerda', max_digits=10, null=True)),
                ('curtose', models.DecimalField(blank=True, decimal_places=6, help_text='Curtose excess: >0 leptocúrtica (caudas pesadas)', max_digits=10, null=True)),
                ('jarque_bera', models.DecimalField(blank=True, decimal_places=4, help_text='Estatística do teste Jarque-Bera de normalidade', max_digits=12, null=True)),
                ('jarque_bera_pvalue', models.DecimalField(blank=True, decimal_places=6, help_text='p-valor do JB: <0.05 rejeita normalidade', max_digits=8, null=True)),
                ('retorno_normal', models.BooleanField(blank=True, help_text='True se JB não rejeita normalidade (p > 0.05)', null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=6, help_text='Beta vs Ibovespa (sensibilidade ao mercado)', max_digits=8, null=True)),
                ('correlacao_ibov', models.DecimalField(blank=True, decimal_places=4, help_text='Correlação de Pearson com o Ibovespa', max_digits=6, null=True)),
                ('r_quadrado', models.DecimalField(blank=True, decimal_places=4, help_text='R² da regressão vs Ibovespa', max_digits=6, null=True)),
                ('media_preco', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('dp_preco', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('preco_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('n_observacoes', models.IntegerField(blank=True, help_text='Número real de pregões usados no cálculo', null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis_estatisticos', to='portfolio.ativo')),
            ],
            options={
                'verbose_name': 'KPI Estatístico',
                'verbose_name_plural': 'KPIs Estatísticos',
                'ordering': ['-data_calculo'],
                'unique_together': {('ativo', 'data_calculo', 'janela_dias')},
            },
        ),
    ]
