# Generated by Django 6.0.1 on 2026-05-01 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('aceita', 'Aceita pelo usuário'), ('ignorada', 'Ignorada')], default='ativa', max_length=10)),
                ('justificativa', models.TextField(blank=True, help_text='Explicação gerada pela IA')),
                ('retorno_esperado', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('volatilidade_esperada', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('sharpe_esperado', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Recomendação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ScoreAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateField()),
                ('score_micro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_macro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_sentimento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_final', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Score do Ativo',
                'ordering': ['-data_calculo', '-score_final'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comprar', 'Comprar'), ('manter', 'Manter'), ('vender', 'Vender'), ('observar', 'Observar')], max_length=10)),
                ('percentual_ideal', models.DecimalField(decimal_places=2, help_text='% sugerido na carteira (soma = 100%)', max_digits=5)),
                ('justificativa_item', models.TextField(blank=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='portfolio.ativo')),
            ],
            options={
                'verbose_name': 'Item da Recomendação',
            },
        ),
    ]
