# Generated by Django 6.0.1 on 2026-05-01 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0002_initial'),
        ('portfolio', '0002_initial'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrecomendacao',
            name='recomendacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='scoring.recomendacao'),
        ),
        migrations.AddField(
            model_name='scoreativo',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='portfolio.ativo'),
        ),
        migrations.AddField(
            model_name='scoreativo',
            name='kpi_macro_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_data.kpimacro'),
        ),
        migrations.AddField(
            model_name='itemrecomendacao',
            name='score_ativo_ref',
            field=models.ForeignKey(blank=True, help_text='Score usado como base da recomendação', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.scoreativo'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreativo',
            unique_together={('ativo', 'data_calculo')},
        ),
        migrations.AlterUniqueTogether(
            name='itemrecomendacao',
            unique_together={('recomendacao', 'ativo')},
        ),
    ]
