# Generated by Django 6.0.1 on 2026-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraRecomendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=20)),
                ('data_calculo', models.DateField(auto_now_add=True)),
                ('composicao', models.JSONField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data_calculo'],
            },
        ),
    ]
