# Generated by Django 6.0.1 on 2026-05-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('subsetor', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'Fundo Imobiliário'), ('etf', 'ETF'), ('bdr', 'BDR'), ('renda_fixa', 'Renda Fixa'), ('crypto', 'Criptomoeda')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Carteira', max_length=100)),
                ('tipo', models.CharField(choices=[('real', 'Carteira Real'), ('simulada', 'Simulação')], default='real', max_length=10)),
                ('patrimonio_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('open_finance_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Carteira',
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=16)),
                ('preco_medio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('percentual_ideal', models.DecimalField(blank=True, decimal_places=2, help_text='% ideal na carteira recomendada', max_digits=5, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posição',
            },
        ),
    ]
