# Generated by Django 6.0.1 on 2026-05-01 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posicao',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='portfolio.ativo'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='portfolio.carteira'),
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together={('carteira', 'ativo')},
        ),
    ]
